services:
  db:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: piazza
      POSTGRES_USER: piazza

volumes:
  postgresql:
